---
# tasks file for ansible

# roles/example/tasks/debian.yml
#- name: Install Packages
#  ansible.builtin.apt:
#    name: "{{item}}"
#    state: present
#  loop: "{{ pkgs }}"
#  become: yes

#
#- name: Create theDr
#  user:
#    name: thedr
#    uid: 2001
#    shell: /bin/bash
#    comment: "Master of the Universe"
#    home: /thedr
#  become: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  become: yes

- name: Install Deb Packages
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ deb_pkgs }}"
  become: yes

- name: Copy DVWA Service Files
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ dvwa }}"

- name: Create xrdp group
  group:
    name: xrdp
  become: yes

- name: Add XRDP to ssl-cert group
  user:
    name: xrdp
    groups: ssl-cert
  become: yes

- name: Restart XRDP
  become: yes
  service:
    name: xrdp
    state: started

- name: Download Zenmap
  become: yes
  get_url:
    url: "https://nmap.org/dist/zenmap-7.91-1.noarch.rpm"
    dest: "/root/zenmap-7.91-1.noarch.rpm"
    mode: 0600

- name: Convert RPM to Deb
  become: yes
  command: alien /root/zenmap-7.91-1.noarch.rpm
  args:
    chdir: "/root"

- name: Install Zenmap
  become: yes
  apt:
    deb: "/root/zenmap_7.91-2_all.deb"
    state: present

- name: Download Nessus
  become: yes
  get_url:
    url: "https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/12207/download?i_agree_to_tenable_license_agreement=true"
    dest: "/root/Nessus-8.13.1-debian6_amd64.deb"
    mode: 0600

- name: Install Nessus
  become: yes
  apt:
    deb: "/root/Nessus-8.13.1-debian6_amd64.deb"
    state: present
